// Diccionario "Edúcate contra el dengue" — 249 palabras del libro
// "Los invasores" (fuente: Diccionario_Edúcate_Contra_el_Dengue.pdf, con
// correcciones de ortografía y contenido hechas en septiembre 2026).
//
// `alias`: otras formas en las que la palabra aparece en el libro (por
// ejemplo "insecticida" → Insecticidas), para que el popup del lector
// también las reconozca.

export type Palabra = { palabra: string; definicion: string; alias?: string[] };

export const DICCIONARIO: Palabra[] = [
  {"palabra": "Abandonados", "definicion": "Palabra que describe a algo o alguien que ha sido dejado solo o desatendido. Puede referirse a objetos, animales o personas que han sido dejados sin cuidado o atención. Es importante brindar apoyo y cuidado a aquellos que se sienten abandonados para ayudarles a superar esa sensación de soledad o desamparo."},
  {"palabra": "Actúe", "definicion": "Es una palabra que significa tomar acción o hacer algo. Cuando se nos dice \"actúe\", nos están indicando que debemos hacer algo específico, como realizar una tarea, tomar una decisión o responder a una situación. Es importante actuar con prontitud y de manera adecuada según lo que se requiera en cada momento."},
  {"palabra": "Adaptando", "definicion": "Ajustar o cambiar algo para que se adecúe mejor a una situación específica. Es como cuando modificas tus acciones o comportamiento para enfrentar un nuevo desafío o situación de manera más efectiva."},
  {"palabra": "Ademanes", "definicion": "Son gestos o movimientos que hacemos con las manos, brazos o cuerpo para expresar algo. Son como señales que usamos al hablar para comunicar emociones, ideas o mensajes. Por ejemplo, agitar las manos al hablar o hacer un gesto de sorpresa son ademanes."},
  {"palabra": "Agazapándose", "definicion": "Significa ponerse en una posición baja y escondida, como agacharse o acurrucarse para evitar ser visto o para sorprender a alguien. Es como cuando un gato se agacha para acechar a su presa."},
  {"palabra": "Agente", "definicion": "Es un organismo o cosa que lleva o facilita la propagación de algo o enfermedades. Por ejemplo, un mosquito puede ser un agente transmisor de enfermedades al picar a una persona infectada y luego picar a otra persona sana, transmitiendo así la enfermedad."},
  {"palabra": "Aglomeró", "definicion": "Es una palabra que describe cuando algo se junta o agrupa en un espacio. Por ejemplo, cuando varias personas o cosas se reúnen en un mismo lugar formando un montón o una masa compacta."},
  {"palabra": "Agravara", "definicion": "Es una forma del verbo \"agravar\", que significa empeorar o hacer más difícil una situación. Por ejemplo, si alguien ya estaba en problemas y esa situación se hace aún peor, se podría decir que se agrava. Es como añadir peso a una carga ya pesada."},
  {"palabra": "Agregó", "definicion": "Es una palabra que se usa para indicar que alguien añadió algo nuevo a una conversación, texto o conjunto de cosas. Significa poner algo extra, como información adicional o un comentario, para enriquecer o completar lo que ya se ha dicho."},
  {"palabra": "Agresivo", "definicion": "comportamientos que son intimidantes o que buscan dañar. Es importante controlar la agresividad para evitar conflictos y promover relaciones saludables."},
  {"palabra": "Aguardaba", "definicion": "Esperar con paciencia a que algo suceda o a alguien llegue. Es como estar en una situación de espera tranquila, sin impaciencia, listo para lo que venga. Por ejemplo, aguardar el autobús o aguardar una respuesta importante."},
  {"palabra": "Agudizaba", "definicion": "Es una forma verbal del verbo \"agudizar\", que significa hacer algo más intenso, profundo o agudo. Por ejemplo, si agudizas tu oído, prestas más atención para escuchar mejor. En resumen, \"agudizaba\" indica el acto de hacer algo más agudo o intenso."},
  {"palabra": "Ahogó", "definicion": "Es la forma pasada del verbo \"ahogar\", que significa dificultad para respirar debido a la falta de aire. También se usa cuando algo se sumerge completamente en agua u otro líquido, impidiendo la respiración. Por ejemplo, \"Se ahogó en el río\" significa que alguien murió por falta de aire bajo el agua."},
  {"palabra": "Ajustándose", "definicion": "Significa hacer cambios o adaptaciones para que algo se adecúe mejor a una situación o necesidad específica. Es como ajustar la correa de un reloj para que quede bien ajustada a la muñeca."},
  {"palabra": "Alarmados", "definicion": "Sentirse asustados o preocupados por algo que puede ser peligroso o amenazante. Es como cuando escuchas una sirena fuerte que te hace sentir que algo malo está sucediendo y te pone nervioso."},
  {"palabra": "Alarmarse", "definicion": "Significa sentir preocupación o nerviosismo repentino debido a una situación inesperada o amenazante. Es cuando te sientes sorprendido y nervioso por algo que te hace sentir en peligro o en riesgo."},
  {"palabra": "Alberca", "definicion": "Es una estructura construida para contener agua, similar a una piscina. Se utiliza comúnmente para nadar o refrescarse en climas cálidos. Puede ser pública o privada y tiene diferentes tamaños y formas. Es un lugar para la recreación y el ejercicio acuático."},
  {"palabra": "Aledañas", "definicion": "Se refiere a las áreas cercanas o contiguas a un lugar específico. Son los lugares que están cerca de algo, como vecindarios próximos a una ciudad o tierras adyacentes a una granja. Es una palabra que describe la proximidad geográfica de un lugar con respecto a otro."},
  {"palabra": "Alistarse", "definicion": "Significa prepararse o ponerse listo para algo, como un evento, una tarea o una situación. Es como cuando te organizas y te equipas para hacer algo importante, como alistarte para ir a una fiesta o alistarte para un examen."},
  {"palabra": "Alivio", "definicion": "Sentirse mejor después de haber pasado por una situación difícil o dolorosa. Es como una sensación de calma y tranquilidad que llega cuando el problema se resuelve o disminuye. Es como un suspiro de alivio después de haber estado preocupado o estresado."},
  {"palabra": "Almacenar", "definicion": "Significa guardar cosas en un lugar específico para usarlas más tarde. Es como guardar juguetes en una caja o guardar comida en la nevera para que estén seguros y ordenados hasta que los necesites."},
  {"palabra": "Alternativas", "definicion": "Son diferentes opciones o posibilidades que se tienen para elegir o hacer algo. Cuando no hay una única escoger la que más nos convenga."},
  {"palabra": "Alucinación", "definicion": "Es cuando ves, oyes, sientes, saboreas o hueles algo que en realidad no está ahí. Es como una ilusión muy real para la persona que la experimenta, pero otros no pueden verla, escucharla, etc. Puede pasar, por ejemplo, con una fiebre muy alta, con algunas enfermedades o cuando alguien no ha dormido."},
  {"palabra": "Alumbraban", "definicion": "Es la forma del verbo \"alumbrar\" en tercera persona del plural del pasado. Significa que en el pasado, algo o alguien proporcionaba luz, iluminando un lugar o situación. Por ejemplo, \"las farolas alumbraban la calle\" indica que las farolas proporcionaban luz en la calle."},
  {"palabra": "Ambiental", "definicion": "Se refiere a todo lo relacionado con el entorno que nos rodea, como el aire, el agua, los animales y las plantas. Trata sobre cómo interactuamos con estos elementos y cómo podemos protegerlos para mantener un equilibrio saludable en nuestro planeta."},
  {"palabra": "Ambiente", "definicion": "Se refiere al entorno que nos rodea, incluyendo el aire, el agua, el suelo, las plantas y los animales. Es todo lo que existe alrededor de un lugar, y es importante cuidarlo porque afecta nuestra salud y el equilibrio de la naturaleza."},
  {"palabra": "Amenaza", "definicion": "Es algo que puede causar daño o peligro. Puede ser una advertencia seria de problemas futuros o una acción que representa riesgo para algo o alguien. Por ejemplo, una tormenta puede ser una amenaza para la seguridad si se acerca a una zona poblada."},
  {"palabra": "Amenazaba", "definicion": "Significa indicar o sugerir un peligro o daño futuro. Es como cuando alguien advierte que algo malo podría pasar, como una tormenta que amenaza con llegar y causar daño."},
  {"palabra": "Analgésicos", "definicion": "Son medicamentos que ayudan a aliviar el dolor. Funcionan bloqueando las señales de dolor enviadas al cerebro, lo que hace que te sientas mejor. Pueden ser útiles para dolores leves o moderados, pero es importante usarlos con precaución y según las indicaciones médicas."},
  {"palabra": "Andanzas", "definicion": "Se refiere a las experiencias, aventuras o caminos recorridos por alguien. Son los eventos emocionantes o interesantes que una persona vive o atraviesa a lo largo de su vida o en un periodo específico."},
  {"palabra": "Angustias", "definicion": "Sustantivo que se refiere a sentimientos de gran preocupación, ansiedad o tormento emocional. Cuando alguien siente angustias, experimenta una sensación de malestar intenso y agobio por situaciones difíciles o problemas emocionales."},
  {"palabra": "Antiaedes", "definicion": "Se refiere a cualquier cosa que combata o prevenga la propagación de mosquitos del género Aedes, como el mosquito transmisor del dengue, zika y chikungunya. Por ejemplo, repelentes, mosquiteros y programas de control de vectores son medidas antiaedes."},
  {"palabra": "Análisis", "definicion": "Es el proceso de examinar algo en detalle para entender su funcionamiento, partes o significado. Implica descomponer algo en sus componentes básicos, estudiar cómo interactúan y sacar conclusiones útiles a partir de esa información. Es como desarmar un rompecabezas para comprender cómo encajan las piezas."},
  {"palabra": "Arbustos", "definicion": "Son plantas pequeñas que tienen varios tallos leñosos y ramificados desde la base. Son más pequeños que los árboles pero más grandes que las hierbas. Suelen tener hojas, flores y frutos, y se encuentran"},
  {"palabra": "Armaron", "definicion": "Palabra que viene del verbo \"armar\". Se usa cuando alguien junta o ensambla partes para crear algo más grande o completo. Por ejemplo, si tú pones piezas de un rompecabezas juntas, estás armando el rompecabezas. En resumen, \"armaron\" significa que alguien organizó o ensambló algo."},
  {"palabra": "Ascendido", "definicion": "Es cuando alguien ha sido promovido a una posición superior, como en un trabajo o en una jerarquía. Es un reconocimiento por su desempeño o habilidades, permitiéndoles avanzar en su carrera o estatus."},
  {"palabra": "Asediado", "definicion": "Significa estar rodeado o atacado constantemente por enemigos. Es como cuando un castillo está rodeado por un ejército enemigo que intenta tomarlo por la fuerza. La gente o lugar asediado enfrenta amenazas constantes y tiene dificultades para salir o defenderse."},
  {"palabra": "Asentarse", "definicion": "Significa establecerse o fijarse en un lugar de manera permanente o temporal. Por ejemplo, cuando alguien se muda a una nueva ciudad y encuentra un hogar donde vivir, se está asentando. Es como arraigar o poner raíces en un lugar."},
  {"palabra": "Asfixiadas", "definicion": "Es el plural femenino del adjetivo \"asfixiado\". Significa que algo o alguien ha experimentado dificultad extrema para respirar, generalmente por falta de aire o por opresión."},
  {"palabra": "Bloqueo", "definicion": "Significa impedir que algo avance o funcione normalmente. Puede referirse a cerrar el paso físico, como una calle bloqueada, o a limitar el acceso a información, como un bloqueo en internet. En resumen, es detener o restringir algo por algún motivo."},
  {"palabra": "Brumosa", "definicion": "Algo que está envuelto en bruma o neblina, es decir, no se ve con claridad. Se usa para describir una situación o ambiente con poca visibilidad debido a la niebla. Por ejemplo, una mañana brumosa es aquella en la que hay mucha neblina y todo parece estar cubierto por una especie de nube baja."},
  {"palabra": "Cabizbajo", "definicion": "Significa tener la cabeza inclinada hacia abajo, generalmente como señal de tristeza, vergüenza o desánimo. Es cuando alguien parece estar con la moral baja o desanimado. Por ejemplo, cuando alguien camina con los hombros caídos y la mirada hacia el suelo."},
  {"palabra": "Campantes", "definicion": "Es una palabra coloquial que se utiliza para describir a alguien que está tranquilo, relajado o sin preocupaciones. Cuando alguien está campante, significa que se siente cómodo y a gusto en su situación actual, sin estrés ni ansiedad."},
  {"palabra": "Caos", "definicion": "Se refiere a un estado de desorden o confusión total, donde las cosas no siguen un patrón predecible o lógico. Es como cuando todo está revuelto y no hay control. Es la ausencia de organización y estructura en cualquier situación."},
  {"palabra": "Cebra", "definicion": "Es un mamífero africano reconocido por sus rayas blancas y negras, que actúan como camuflaje en la hierba alta. Vive en manadas, alimentándose de plantas y evitando a los depredadores."},
  {"palabra": "Celos", "definicion": "Sentimiento que aparece cuando una persona siente miedo de perder algo que considera valioso, como la atención o el cariño de alguien. Puede surgir cuando esa persona ve que alguien más recibe la atención que ellos desean. Los celos pueden causar incomodidad e inseguridad."},
  {"palabra": "Certezas", "definicion": "Son aquellas cosas que estamos seguros de que son ciertas o verdaderas. Son como respuestas seguras a preguntas, sin dudas. Por ejemplo, cuando sabemos con seguridad que el sol saldrá cada mañana, eso es una certeza."},
  {"palabra": "Clandestinamente", "definicion": "Realizar algo en secreto o de manera oculta, sin que otras personas lo sepan o lo aprueben. Por ejemplo, realizar una actividad clandestinamente implica que se hace sin permiso o fuera de la vista de autoridades o personas relevantes."},
  {"palabra": "Coincidieron", "definicion": "Significa que dos o más cosas sucedieron al mismo tiempo o de manera simultánea. Es como si dos personas estuvieran pensando en lo mismo o experimentando algo similar al mismo tiempo. Es un término que describe cuando las situaciones se alinean o concuerdan entre sí."},
  {"palabra": "Concentrado", "definicion": "Significa que algo está reunido en un solo lugar, en gran cantidad o densidad. Por ejemplo, un jugo concentrado es aquel en el que se ha eliminado el agua para tener más sabor en menos volumen. Es como si algo estuviera muy enfocado o lleno en una sola cosa."},
  {"palabra": "Condición", "definicion": "Se refiere a la manera en que algo o alguien se encuentra en un momento dado. Es como una característica o estado que define cómo es algo o alguien en ciertas circunstancias. Por ejemplo, la salud de una persona, la situación de un objeto o las reglas para realizar algo pueden ser condiciones."},
  {"palabra": "Conmocionado", "definicion": "Significa sentirse muy afectado emocional o físicamente debido a un evento impactante o sorprendente. Es como cuando algo te deja aturdido o te sacude tanto que te resulta difícil procesarlo. Por ejemplo, puedes sentirte conmocionado después de presenciar un accidente grave."},
  {"palabra": "Constante", "definicion": "Se refiere a algo que permanece igual o invariable a lo largo del tiempo. Es como una característica o una cualidad que no cambia. Por ejemplo, si dices que alguien es \"constante en su trabajo\", significa que esa persona siempre trabaja de la misma manera, sin importar las circunstancias."},
  {"palabra": "Contagioso", "definicion": "Significa que algo, como una enfermedad o una emoción, puede transmitirse fácilmente de una persona a otra. Cuando algo es contagioso, se propaga rápidamente de un individuo a otro, como un resfriado que se transmite al toser o estornudar."},
  {"palabra": "Contrarrestar", "definicion": "Significa neutralizar o hacer menos efectivo algo negativo o dañino. Es como cuando usas un paraguas para contrarrestar la lluvia, o tomas medicina para contrarrestar los síntomas de un resfriado. Es tomar medidas para contrarrestar un problema o situación no deseada."},
  {"palabra": "Controlado", "definicion": "Significa que algo está regulado o supervisado de manera ordenada y consciente. Cuando algo está bajo control, se maneja de manera adecuada y se evitan problemas o situaciones no deseadas. Por ejemplo, un incendio controlado es uno que se gestiona para evitar que se propague sin control."},
  {"palabra": "Contundentes", "definicion": "Significa que algo es muy claro, fuerte o convincente. Se refiere a argumentos o pruebas que son muy poderosos y difíciles de rebatir. Por ejemplo, si alguien presenta datos sólidos que respaldan su punto de"},
  {"palabra": "Cortejaba", "definicion": "Es un verbo que describe el acto de mostrar interés romántico hacia alguien. Cuando alguien corteja a otra persona, busca ganarse su afecto y atención de manera delicada y respetuosa, a menudo a través de gestos amables, halagos y muestras de cariño. Es como el primer paso para iniciar una relación amorosa."},
  {"palabra": "Cruzara", "definicion": "Es una palabra que se usa para describir el acto de ir de un lado a otro sobre algo, como una calle o un río. También puede referirse a atravesar obstáculos o dificultades. Por ejemplo, \"si alguien cruzara el río por un puente\" significa que pasaría de un lado al otro del río usando un puente."},
  {"palabra": "Cuarentena", "definicion": "Es un período de tiempo en el que una persona o comunidad se aísla para prevenir la propagación de enfermedades. Durante la cuarentena, se limitan las interacciones sociales y se sigue de cerca la salud de las personas para evitar contagios."},
  {"palabra": "Curioso", "definicion": "Es alguien o algo que tiene un gran interés en descubrir y aprender sobre cosas nuevas o desconocidas. También puede referirse a algo que es extraño o inusual. Ser curioso implica querer explorar y entender el mundo que nos rodea con curiosidad y asombro."},
  {"palabra": "Decidida", "definicion": "Significa que una persona ha tomado una decisión con firmeza y determinación. Es cuando alguien ha pensado bien en algo y está seguro de lo que quiere hacer, sin dudarlo. Por ejemplo, si una persona está \"decidida\" a estudiar medicina, significa que está completamente segura y comprometida con esa elección."},
  {"palabra": "Deliraba", "definicion": "Es un verbo que describe cuando alguien habla o piensa de manera confusa o irracional, generalmente debido a la fiebre, enfermedad mental o intoxicación. Por ejemplo, alguien que está delirando podría decir cosas sin sentido o creer en cosas que no son reales."},
  {"palabra": "Delirante", "definicion": "Es un adjetivo que describe algo extravagante, fuera de lo común o irracional. Se usa para referirse a ideas, acciones o situaciones que son exageradas o absurdas. Por ejemplo, una película con un argumento muy extraño podría ser descrita como delirante."},
  {"palabra": "Dengue", "definicion": "El dengue es una enfermedad viral transmitida por mosquitos, principalmente por el mosquito Aedes aegypti, aunque también puede ser transmitida por el Aedes albopictus. Es común en áreas tropicales y subtropicales del mundo, incluyendo partes de África, el sudeste asiático, el Pacífico occidental y las Américas. El virus del dengue pertenece a la familia Flaviviridae y existen cuatro serotipos diferentes (DEN-1, DEN-2, DEN-3 y DEN-4), todos capaces de causar la enfermedad."},
  {"palabra": "Deposiciones", "definicion": "Son los desechos sólidos o líquidos que nuestro cuerpo elimina a través del recto. Son el resultado final del proceso de digestión, incluyendo alimentos no digeridos, bacterias y productos de desecho. Su aspecto y frecuencia pueden variar dependiendo de la dieta y la salud."},
  {"palabra": "Desconfiados", "definicion": "Es un adjetivo que describe a las personas que no confían fácilmente en los demás. Son cautelosos y dudan de las intenciones de los demás. Esta actitud puede surgir por experiencias pasadas o por naturaleza."},
  {"palabra": "Descontroladas", "definicion": "Se refiere a cosas o situaciones que no están siendo reguladas o manejadas adecuadamente. Es cuando algo está sin control o sin orden, lo que puede llevar a problemas o caos. Por ejemplo, si hay multitudes descontroladas, significa que no están siendo supervisadas o dirigidas, lo que puede resultar en comportamientos peligrosos o destructivos."},
  {"palabra": "Desfile", "definicion": "Un evento donde las personas caminan o marchan en fila, mostrando vestimenta especial, arte o habilidades. Puede ser para celebrar algo, como un desfile militar, o para presentar moda en pasarelas. Es una exhibición pública que a menudo se realiza en calles o lugares especiales."},
  {"palabra": "Deshidratación", "definicion": "Cuando el cuerpo pierde más líquido de lo que ingiere. Esto puede ocurrir por no beber suficiente agua, sudar mucho o enfermarse. Provoca síntomas como sed extrema, boca seca, mareos y debilidad. Es importante beber líquidos para evitarla."},
  {"palabra": "Desilusionado", "definicion": "Significa sentirse decepcionado o desencantado cuando algo o alguien no cumple nuestras expectativas o ilusiones. Es como cuando esperábamos algo bueno pero no sucede como esperábamos, lo que nos hace sentir tristes o desmotivados."},
  {"palabra": "Desvanecía", "definicion": "Es una palabra que se refiere a cuando algo o alguien va perdiendo su intensidad o presencia gradualmente, como si se estuviera desapareciendo o desapareciendo poco a poco. Por ejemplo, una imagen que se desvanece en la distancia se va volviendo menos clara hasta que ya no se puede ver."},
  {"palabra": "Difamados", "definicion": "Término que se refiere a personas que han sido objeto de comentarios falsos o maliciosos que dañan su reputación o imagen pública. Cuando alguien difama a otra persona, está haciendo afirmaciones negativas sobre ella que pueden no ser ciertas. Ser difamado puede causar mucho daño emocional y perjudicar la forma en que otras personas ven a esa persona."},
  {"palabra": "Distraído", "definicion": "Estar desenfocado o distraído de algo importante debido a la falta de atención o concentración. Cuando una persona está distraída, tiende a perder el enfoque en lo que está haciendo o lo que le están diciendo."},
  {"palabra": "Documentación", "definicion": "Conjunto de papeles, archivos o registros que sirven para respaldar información importante sobre algo. Puede incluir instrucciones, evidencia o detalles necesarios para entender o completar una tarea, proyecto o proceso."},
  {"palabra": "Eclosionado", "definicion": "Se refiere al momento en que un huevo o una crisálida se abre y la criatura que estaba dentro emerge. Es como cuando una mariposa sale de su capullo o un polluelo sale de su cascarón. Es un proceso de nacimiento o liberación muy especial en el mundo natural.", "alias": ["eclosionan"]},
  {"palabra": "Embaucadores", "definicion": "Se refiere a personas que engañan o manipulan a otros para obtener beneficios personales. Son individuos astutos que utilizan la persuasión o la astucia para engañar a otros de manera deshonesta."},
  {"palabra": "Endovenosa", "definicion": "Algo que se administra dentro de una vena, usualmente mediante una inyección o goteo. Es una forma de introducir medicamentos o líquidos directamente en el torrente sanguíneo para que actúen rápidamente en el cuerpo."},
  {"palabra": "Enjambre", "definicion": "Es un término que describe a un grupo grande de insectos, como abejas o avispas, que vuelan juntos en una especie de nube. También se usa para referirse a una multitud de personas o cosas apiñadas o agrupadas. Es como cuando ves muchas abejas volando juntas o una gran cantidad de personas reunidas en un lugar."},
  {"palabra": "Enjambres", "definicion": "Se refiere a grandes grupos de estos insectos voladores que se reúnen y vuelan juntos. Son comunes en áreas húmedas y pueden ser molestos debido a sus picaduras. Estos enjambres suelen encontrarse cerca de fuentes de agua donde depositan sus huevos."},
  {"palabra": "Epidemias", "definicion": "Son brotes de enfermedades que afectan a muchas personas en una región específica o en varias partes del mundo al mismo tiempo. Pueden propagarse rápidamente y causar problemas de salud pública, como el DENGUE. Es importante tomar medidas preventivas para controlarlas."},
  {"palabra": "Escarbó", "definicion": "Es una forma del verbo \"escarbar\". Significa mover la tierra o cualquier otra superficie con las manos o las patas para encontrar algo, como comida o un objeto enterrado. Es una acción común entre ciertos animales y también puede referirse a una búsqueda minuciosa o investigativa en contextos humanos."},
  {"palabra": "Escena", "definicion": "Es como una parte de una historia o evento. Es donde suceden cosas específicas, como en una película, obra de teatro o en la vida real. En una escena, los personajes interactúan y se desarrolla la trama. Es como una pequeña ventana que muestra lo que está pasando en ese momento y lugar."},
  {"palabra": "Escondites", "definicion": "Son lugares secretos donde las personas guardan o se ocultan cosas. Pueden ser detrás de muebles, en armarios o en el jardín. Son utilizados en juegos como el escondite o para guardar objetos de valor de manera segura."},
  {"palabra": "Esparcieron", "definicion": "En relación con insectos del dengue significa que se dispersaron o distribuyeron por diferentes áreas. Por ejemplo, si decimos que los mosquitos portadores del dengue se esparcieron por un vecindario, significa que se propagaron por distintos lugares de esa zona, aumentando el riesgo de transmisión de la enfermedad."},
  {"palabra": "Esparcían", "definicion": "Es el verbo en pasado de \"esparcir\", que significa distribuir o diseminar algo de manera uniforme en diferentes direcciones. Por ejemplo, cuando se esparcen semillas en un jardín, se distribuyen de manera uniforme por toda el área."},
  {"palabra": "Especialista", "definicion": "Alguien que tiene un conocimiento profundo y específico sobre un tema o área en particular. Es como un experto en algo específico, como un médico especializado en una rama de la medicina o un técnico con habilidades específicas en su campo."},
  {"palabra": "Estabilizar", "definicion": "Significa hacer que algo se mantenga constante o equilibrado, evitando cambios o movimientos bruscos. Es como cuando pones una mesa coja para que no se tambalee. En resumen, es mantener algo firme y sin cambios drásticos."},
  {"palabra": "Estela", "definicion": "Es la huella que deja algo al pasar, como un barco en el mar o un avión en el cielo. También puede ser una columna de humo, luz o vapor que se forma detrás de un objeto en movimiento. Además, se usa para nombrar a una obra o testimonio que perdura en la memoria de las personas."},
  {"palabra": "Estragos", "definicion": "Se refiere a los daños o efectos negativos causados por un evento o situación. Esas consecuencias ejemplo, un desastre natural puede causar estragos en una comunidad, dejando destrucción y sufrimiento a su paso."},
  {"palabra": "Estricta", "definicion": "Significa seguir reglas o normas de manera muy precisa y sin flexibilidad. Algo o alguien que es estricto es firme en hacer cumplir las reglas y no permite desviaciones. Por ejemplo, una profesora estricta puede exigir que los estudiantes sigan todas las instrucciones al pie de la letra."},
  {"palabra": "Estricto", "definicion": "Significa que alguien o algo es muy preciso y no permite errores o desviaciones. Una persona estricta puede seguir reglas muy rigurosas o exigir un alto nivel de cumplimiento. Por ejemplo, un maestro estricto podría requerir que los estudiantes sigan todas las instrucciones al pie de la letra."},
  {"palabra": "Euforia", "definicion": "Es una sensación de felicidad extrema y excitación. Es como sentirte en la cima del mundo, lleno de energía positiva y alegría. Puede ser causada por algo emocionante o gratificante, como lograr un objetivo importante o recibir buenas noticias."},
  {"palabra": "Exceso", "definicion": "Es cuando tienes más de lo necesario o adecuado. Por ejemplo, comer demasiado dulce puede causar un exceso de azúcar en tu cuerpo. También se puede referir a hacer algo en exageración, como gastar mucho dinero en algo innecesario. Es importante encontrar un equilibrio para evitar los excesos y mantenernos saludables y responsables."},
  {"palabra": "Expandirse", "definicion": "Significa crecer o extenderse en todas direcciones. Es como cuando un globo se infla y se vuelve más grande, ocupando más espacio a su alrededor. En términos más simples, es aumentar en tamaño o alcance."},
  {"palabra": "Expectativa", "definicion": "Significa esperar algo con la idea de que suceda. Es como tener una imagen en tu mente de lo que podría pasar y sentir curiosidad por ver si se cumple. Por ejemplo, cuando esperas con emoción el resultado de algo o tienes una idea de cómo será algo en el futuro."},
  {"palabra": "Expertas", "definicion": "Plural femenino de \"experto\". Se refiere a personas que tienen un alto nivel de conocimiento o habilidad en un área específica. Son personas que han estudiado, practicado o tienen mucha experiencia en algo en particular, lo que les permite ofrecer consejos, resolver problemas o tomar decisiones con confianza y precisión."},
  {"palabra": "Exposición", "definicion": "En el contexto del dengue significa entrar en contacto con mosquitos portadores del virus. Cuando una persona está expuesta al dengue, significa que ha estado en un área donde hay mosquitos infectados y podría contraer la enfermedad si es picada."},
  {"palabra": "Expresando", "definicion": "Es un verbo que significa comunicar o manifestar algo, ya sea mediante palabras, gestos, acciones o escritura. Es la forma en que mostramos nuestros pensamientos, sentimientos o ideas a los demás, permitiendo que nos entiendan mejor. Por ejemplo, expresamos amor con un abrazo, alegría con una sonrisa o pensamientos con palabras."},
  {"palabra": "Exterminadores", "definicion": "Es el plural de \"exterminador\", que se refiere a personas o cosas que eliminan por completo algo, como insectos, plagas o enemigos. Son conocidos por su habilidad para acabar con una amenaza o problema de manera efectiva y completa."},
  {"palabra": "Exterminados", "definicion": "Es una palabra que se refiere a la acción de eliminar completamente algo, usualmente se usa para describir la destrucción total de plagas, enfermedades o poblaciones de organismos. Es como decir que algo ha sido totalmente eliminado o erradicado."},
  {"palabra": "Extracto", "definicion": "Es una parte pequeña o resumida de algo más grande. Es como sacar lo más importante de un texto, de una historia o de una planta. Por ejemplo, un extracto de un libro es un pedacito del libro, y un extracto de fruta es lo concentrado de su sabor."},
  {"palabra": "Fantasmitas", "definicion": "Es una palabra cariñosa que se refiere a pequeñas apariciones o figuras fantasmales. Puede usarse para describir algo sutil o ligeramente misterioso, como las pequeñas sombras que a veces vemos de rabillo del ojo. Es como llamar \"pequeños fantasmas\" de manera amigable y juguetona."},
  {"palabra": "Farsante", "definicion": "Palabra que se usa para describir a alguien que finge ser algo que no es, especialmente en relación con su carácter, habilidades o intenciones. Es alguien que engaña o actúa de manera fraudulenta para obtener beneficios o atención de manera deshonesta."},
  {"palabra": "Fase", "definicion": "Es una etapa o parte de un proceso. Por ejemplo, en un juego, la fase de preparación es cuando te estás preparando, y la fase de acción es cuando realmente estás jugando. En la vida, las fases son momentos específicos que atraviesas mientras creces, aprendes o experimentas algo nuevo."},
  {"palabra": "Finalidad", "definicion": "Es el propósito o motivo detrás de algo que se hace. Es la razón por la cual se realiza una acción o se crea algo, indicando el objetivo que se desea alcanzar. Por ejemplo, la finalidad de estudiar es aprender y obtener conocimientos."},
  {"palabra": "Flamante", "definicion": "Se refiere a algo nuevo, recién estrenado o en perfecto estado. Por ejemplo, un carro flamante es uno que acaba de salir de la tienda y está impecable. Es como cuando estrenas algo y brilla como nuevo."},
  {"palabra": "Frenética", "definicion": "Significa algo que está muy agitado, rápido o caótico. Cuando algo es frenético, está lleno de actividad intensa y desordenada, como una situación donde todo sucede muy rápido y sin control. Por ejemplo, una carrera de autos puede ser frenética porque hay mucha velocidad y movimiento caótico."},
  {"palabra": "Fuente", "definicion": "En relación al dengue se refiere al lugar donde los mosquitos portadores del virus encuentran agua estancada para reproducirse, como charcos, recipientes de agua abandonados o desechos. Estos sitios son \"fuentes\" de cría de mosquitos, contribuyendo así a la propagación del dengue."},
  {"palabra": "Fugitivos", "definicion": "Son personas que huyen o escapan de algo, como la justicia o una situación peligrosa. Pueden ser buscados por la policía o estar en riesgo. Su objetivo es evitar ser capturados o descubiertos."},
  {"palabra": "Fumigar", "definicion": "Significa rociar o pulverizar sustancias químicas, como insecticidas o pesticidas, sobre plantas o áreas para eliminar insectos, plagas o enfermedades. Este proceso ayuda a proteger cultivos y áreas contra daños causados por organismos no deseados."},
  {"palabra": "Galanteos", "definicion": "Acciones o comportamientos que una persona realiza para demostrar interés romántico o cortesía hacia otra. Incluye gestos amables, cumplidos y atenciones que se hacen para conquistar o enamorar a alguien. Es parte del cortejo o proceso de seducción en las relaciones interpersonales."},
  {"palabra": "Gestión", "definicion": "Es una forma en que se planifican, organizan, dirigen y controlan actividades o recursos para lograr un objetivo específico, como administrar una empresa o llevar a cabo un proyecto. Se requiere coordinación, toma de decisiones y seguimiento para alcanzar el éxito."},
  {"palabra": "Haraganes", "definicion": "Se refiere a personas que son perezosas o que les gusta evitar el trabajo. Son aquellos que prefieren no hacer mucho y pasar el tiempo sin hacer nada productivo. En resumen, son personas que tienen una aversión al trabajo o a la actividad."},
  {"palabra": "Hazaña", "definicion": "Es una acción valiente, difícil o extraordinaria que alguien logra con mucho esfuerzo. Por ejemplo, rescatar a alguien en peligro o vencer un gran reto es una hazaña. Los héroes de las historias son recordados por sus hazañas."},
  {"palabra": "Hazmerreír", "definicion": "Es una palabra que se usa para describir a alguien o algo que provoca risa o burla, generalmente por comportamientos tontos o ridículos. Es como decir \"el objeto de risa\" o \"la persona que se hace el ridículo\". Por ejemplo, un payaso que hace travesuras puede ser considerado un hazmerreír."},
  {"palabra": "Huevecillos", "definicion": "Son diminutas estructuras donde se desarrollan huevos de animales como insectos, peces o anfibios. Pueden encontrarse en agua, plantas o suelos. Son importantes para la reproducción de estos seres y pueden ser visibles a simple vista o requerir microscopio para su observación."},
  {"palabra": "Ideó", "definicion": "Es la forma conjugada del verbo \"idear\". Significa pensar en algo de manera creativa para inventar, diseñar o planificar algo nuevo. Cuando alguien \"idea\", está imaginando soluciones o creando conceptos innovadores para resolver problemas o desarrollar proyectos."},
  {"palabra": "Improvisada", "definicion": "Algo que se hace sin planear o preparar de antemano. Es como cuando cocinas sin receta: tomas lo que tienes y creas algo en el momento. Una obra improvisada es como una actuación sin ensayo previo. Es hacer algo sobre la marcha, sin mucha preparación."},
  {"palabra": "Incrementar", "definicion": "Aumentar o hacer más grande una cantidad, tamaño o valor. Por ejemplo, si tienes 5 manzanas y añades 3 más, incrementas el número total de manzanas a 8. Es como hacer crecer algo o hacerlo mejor."},
  {"palabra": "Inerte", "definicion": "Significa que algo no tiene la capacidad de moverse o reaccionar por sí mismo. Es como un objeto que está quieto y no responde a ningún estímulo. Por ejemplo, una roca en el suelo es inerte porque no puede moverse ni hacer nada por sí misma."},
  {"palabra": "Infecciosas", "definicion": "Se refiere a enfermedades causadas por gérmenes como bacterias, virus, hongos o parásitos. Estas incluyen resfriados, gripe, tuberculosis, dengue o COVID-19."},
  {"palabra": "Infectadas", "definicion": "Es una palabra que se usa para describir algo o alguien que ha sido contaminado por un agente patógeno, como un virus o una bacteria, lo que puede causar enfermedad o propagar la infección a otras personas. Por ejemplo, si alguien tiene gripe, pueden decir que están infectadas con el virus de la gripe."},
  {"palabra": "Infectología", "definicion": "Es la rama de la medicina que se enfoca en el estudio, prevención, diagnóstico y tratamiento de las enfermedades causadas por organismos como bacterias, virus, hongos y parásitos. Los infectólogos investigan cómo se propagan estas enfermedades y desarrollan estrategias para controlarlas y tratarlas."},
  {"palabra": "Insecticidas", "definicion": "Son productos químicos diseñados para matar insectos que pueden dañar cultivos, transmitir enfermedades o ser molestos. Se aplican en forma de aerosol, polvo o líquido para controlar plagas y proteger plantas y espacios habitados de los insectos no deseados.", "alias": ["insecticida"]},
  {"palabra": "Insectos", "definicion": "Son animales pequeños que tienen tres partes del cuerpo: la cabeza, el tórax y el abdomen. Por lo general, tienen seis patas y a veces alas. Pueden vivir en muchos lugares diferentes, desde el suelo hasta el aire. Hay muchos tipos diferentes de insectos, como las hormigas, las mariposas, los escarabajos y las moscas."},
  {"palabra": "Inservibles", "definicion": "Es un término que describe cosas que no son útiles o no sirven para su propósito previsto. Por ejemplo, objetos rotos o desgastados que ya no pueden cumplir su función. Es importante desechar o reparar los objetos inservibles para mantener un entorno ordenado y funcional."},
  {"palabra": "Instalaron", "definicion": "Es una palabra que se refiere a la acción de colocar o poner algo en su lugar adecuado para que funcione correctamente. En resumen, \"instalaron\" significa poner algo en su sitio para que pueda ser utilizado."},
  {"palabra": "Intenciones", "definicion": "Se refiere a los propósitos o planes que una persona tiene al hacer algo. Son las razones detrás de nuestras acciones, lo que queremos lograr o conseguir. Por ejemplo, si alguien ayuda a otro, sus intenciones podrían ser ser amable o hacer el bien."},
  {"palabra": "Intensivos", "definicion": "Se refiere a actividades, tratamientos o cursos que requieren mucha concentración y esfuerzo en un corto período de tiempo. Son programas que se realizan de manera profunda y concentrada para lograr resultados rápidos y efectivos."},
  {"palabra": "Inundaron", "definicion": "Significa que los lugares fueron cubiertos por una gran cantidad de agua. Por ejemplo, cuando hay aguas estancadas después de la lluvia, pueden \"inundarse\" los lugares donde los mosquitos que propagan el dengue ponen sus huevos."},
  {"palabra": "Invadido", "definicion": "En el contexto de la propagación del dengue significa que un área ha sido afectada o colonizada por el virus del dengue, transmitido por mosquitos. Indica que la enfermedad se ha extendido y está presente en esa zona, poniendo en riesgo la salud de las personas."},
  {"palabra": "Invasor", "definicion": "Describe a los mosquitos que transmiten el dengue. Son pequeños insectos que entran en áreas donde no pertenecen, como casas y comunidades, propagando la enfermedad al picar a las personas."},
  {"palabra": "Investigar", "definicion": "Buscar información o respuestas sobre algo. Es como ser un detective que busca pistas para resolver un nuevas."},
  {"palabra": "Irresponsable", "definicion": "Termino que significa que una persona no cumple con sus deberes o compromisos de manera adecuada. Se comporta de manera descuidada o negligente, sin pensar en las consecuencias de sus acciones."},
  {"palabra": "Irritación", "definicion": "Se presenta como una sensación molesta o incómoda que experimentamos cuando algo nos causa molestia, enojo o malestar. Puede ser física, como cuando nos pica la piel, o emocional, como cuando nos frustramos por algo. Es una reacción natural del cuerpo o la mente ante estímulos desagradables."},
  {"palabra": "Jeringa", "definicion": "Instrumento médico utilizado para inyectar líquidos en el cuerpo o extraerlos de él. Consiste en un cilindro hueco con una aguja en un extremo y un émbolo en el otro. Se utiliza en hospitales y consultorios médicos para administrar medicamentos, extraer sangre para análisis y realizar otras intervenciones médicas."},
  {"palabra": "Jornadas", "definicion": "Son períodos específicos de tiempo dedicados a realizar ciertas actividades, como conferencias, talleres o eventos. Por ejemplo, las jornadas laborales son el tiempo que una persona trabaja durante el día. Estas jornadas pueden variar en duración dependiendo del contexto."},
  {"palabra": "Laboriosa", "definicion": "Es un adjetivo que se utiliza para describir a una persona o cosa que requiere mucho esfuerzo y trabajo duro para completarse o llevarse a cabo. Es algo que implica dedicación, tiempo y energía para lograrlo. Por ejemplo, una tarea laboriosa sería aquella que demanda mucho tiempo y concentración para realizarla satisfactoriamente."},
  {"palabra": "Larvas", "definicion": "Son las formas juveniles de algunos insectos, como mosquitos o mariposas, que aún no han alcanzado su forma adulta. Generalmente son pequeñas y pueden tener aspecto de gusano. Durante esta etapa, se alimentan y crecen antes de convertirse en adultos."},
  {"palabra": "Letales", "definicion": "Es un adjetivo que se usa para describir algo que puede causar la muerte o ser muy peligroso. Por ejemplo, ciertas sustancias químicas o enfermedades pueden ser letales si no se manejan adecuadamente. Es importante tener precaución con cosas letales para evitar accidentes graves."},
  {"palabra": "Liderazgo", "definicion": "La habilidad para guiar, inspirar y motivar a otros hacia un objetivo común. Implica tomar decisiones, comunicarse de manera efectiva y ser un ejemplo a seguir. Un líder muestra empatía, resuelve problemas y fomenta el crecimiento tanto personal como del equipo."},
  {"palabra": "Lozanía", "definicion": "Se refiere a la cualidad de algo que está fresco, vigoroso y lleno de vitalidad. Por ejemplo, podrías usarla para describir a una persona joven y llena de energía, o para describir la apariencia saludable y vibrante de un jardín o una planta."},
  {"palabra": "Lupa", "definicion": "Una lupa es una herramienta óptica pequeña que ayuda a ampliar objetos pequeños para que puedan ser vistos con más claridad. Funciona al enfocar la luz a través de una lente convexa, lo que hace que los objetos cercanos parezcan más grandes cuando se miran a través de ella."},
  {"palabra": "Lúdica", "definicion": "Se refiere a actividades que son divertidas, creativas e involucran juego. Es aprender mientras te diviertes, usando juegos y actividades para enseñar y desarrollar habilidades. Es una forma de aprender que hace que el proceso sea más divertido y efectivo."},
  {"palabra": "Malestar", "definicion": "Es cuando no te sientes bien física o emocionalmente. Puedes sentir dolor, incomodidad o preocupación. Es como una señal de tu cuerpo o mente de que algo no está bien y necesitas cuidarte."},
  {"palabra": "Maleza", "definicion": "Se refiere a las plantas no deseadas que crecen en lugares no planificados, como jardines o campos de cultivo. Son difíciles de controlar y pueden competir con las plantas cultivadas por recursos como agua y nutrientes."},
  {"palabra": "Malhumorado", "definicion": "Es una palabra que describe a alguien que está de mal humor o de mal genio. Cuando una persona está malhumorada, es probable que esté irritable, gruñona o molesta por alguna razón. Puede expresar su disgusto con gestos o comentarios desagradables hacia los demás."},
  {"palabra": "Mandatario", "definicion": "Persona que tiene el poder de representar a otros y tomar decisiones en su nombre. Por lo general, es elegido o designado para ejercer autoridad en un país o una organización. Es responsable de cumplir con las funciones y deberes que le han sido confiados por quienes lo eligieron o nombraron."},
  {"palabra": "Manifestaron", "definicion": "Significa expresar o comunicar algo claramente, ya sea a través de palabras, acciones o gestos. Es mostrar lo que se piensa, siente o desea de manera evidente y comprensible para los demás. Por ejemplo, alguien puede manifestar su amor mediante palabras cariñosas o gestos afectuosos."},
  {"palabra": "Mejoría", "definicion": "Significa que algo está mejorando o volviéndose mejor. Es cuando una situación, condición o estado cambia positivamente, ya sea en salud, ánimo o calidad. Por ejemplo, si te enfermas y luego te sientes un poco mejor cada día, estás experimentando una mejoría."},
  {"palabra": "Militarizada", "definicion": "Significa que algo está bajo control o influencia del ejército. Puede referirse a una región donde los soldados tienen un papel importante en la seguridad o a una situación donde se aplican medidas o estrategias típicas del ámbito militar."},
  {"palabra": "Minuciosamente", "definicion": "Significa hacer algo con gran atención a los detalles y con cuidado meticuloso. Es como examinar algo muy de cerca, prestando atención a cada pequeña parte o aspecto para entenderlo o realizarlo correctamente."},
  {"palabra": "Modesta", "definicion": "Significa que una persona o cosa no es excesivamente orgullosa o presumida. Es alguien o algo que no busca llamar la atención o destacar demasiado. Una persona modesta es humilde y no alardea de sus logros o posesiones."},
  {"palabra": "Moradores", "definicion": "Se refiere a las personas que viven o habitan en un lugar específico. Son los residentes o habitantes de una zona, comunidad o lugar determinado. Es una palabra que describe a las personas que tienen su hogar en un sitio particular."},
  {"palabra": "Mortalidad", "definicion": "específico. Es una medida importante para comprender la salud de una comunidad o país."},
  {"palabra": "Mosquitos", "definicion": "Es el plural de la palabra \"mosquito\". Un mosquito es un insecto pequeño que generalmente pica a los seres humanos y a otros animales para alimentarse de su sangre. Pueden ser molestos porque su picadura causa picazón y a veces pueden transmitir enfermedades. Los mosquitos suelen zumbar al volar y son comunes en lugares donde hay agua estancada, ya que ahí es donde ponen sus huevos."},
  {"palabra": "Multiplicaban", "definicion": "En el contexto de los insectos del dengue se refiere a la reproducción rápida y abundante de los mosquitos portadores del virus del dengue. Es decir, los mosquitos se están reproduciendo en grandes cantidades, lo que aumenta el riesgo de propagación de la enfermedad."},
  {"palabra": "Murmuraron", "definicion": "Palabra que describe el sonido suave y repetitivo que hacen las personas cuando hablan en voz baja, como si estuvieran hablando entre dientes o susurrando. Es como un murmullo o un susurro que se escucha de manera tenue."},
  {"palabra": "Mérito", "definicion": "Reconocimiento que recibes por hacer algo bien o lograr algo importante. Es como un premio que ganas por tu esfuerzo, habilidad o talento. Es demostrar que te lo mereces por tus acciones o cualidades positivas."},
  {"palabra": "Nervioso", "definicion": "Describe sentirse inquieto, ansioso o tenso. Cuando estás nervioso, tu cuerpo puede sentirse agitado y tu mente preocupada. Puedes experimentar sudoración, temblores o dificultad para concentrarte. Es una sensación común ante situaciones estresantes o emocionantes."},
  {"palabra": "Paciencia", "definicion": "Capacidad de mantener la calma y esperar con tranquilidad, incluso cuando las cosas no van como esperamos. Es como tener un superpoder que nos ayuda a enfrentar los desafíos sin enojarnos ni rendirnos fácilmente, permitiéndonos manejar situaciones difíciles con serenidad y perseverancia."},
  {"palabra": "Pacientes", "definicion": "Término que se refiere a las personas que reciben atención médica o tratamiento por parte de profesionales de la salud, como médicos y enfermeras. Estas personas pueden estar enfermas, heridas o necesitar cuidados especiales para recuperarse. Ser paciente también implica tener calma y esperar durante el proceso de atención médica."},
  {"palabra": "Padecer", "definicion": "Significa experimentar dolor, sufrimiento o dificultades. Cuando alguien padece, está sintiendo malestar físico o emocional. Por ejemplo, una persona puede padecer de una enfermedad, lo que significa que está sufriendo sus síntomas."},
  {"palabra": "Patología", "definicion": "Es el estudio de las enfermedades. Examina las causas, procesos y efectos de las enfermedades en el cuerpo humano. Ayuda a comprender cómo funcionan las enfermedades y cómo afectan a los órganos y tejidos."},
  {"palabra": "Percatarse", "definicion": "Significa darse cuenta o notar algo. Es cuando te das cuenta de algo que no habías notado antes, como tu alrededor."},
  {"palabra": "Percató", "definicion": "Es una palabra que significa darse cuenta o notar algo de manera consciente. Cuando alguien se percata de algo, significa que ha observado o comprendido algo que antes no había notado. Es como si una luz se encendiera en su mente, haciéndoles conscientes de algo importante."},
  {"palabra": "Pertinentes", "definicion": "Algo que es relevante o adecuado para la situación o contexto en el que se encuentra. Son aquellas cosas que tienen una conexión directa o importante con lo que se está discutiendo o tratando en ese momento."},
  {"palabra": "Peste", "definicion": "Se refiere a una enfermedad contagiosa que afecta a muchas personas o animales al mismo tiempo. Suele causar síntomas graves y puede propagarse rápidamente. Ejemplos incluyen la peste bubónica o la gripe pandémica. Es importante tomar medidas para prevenir su propagación, como la higiene y la vacunación."},
  {"palabra": "Piquiña", "definicion": "Sensación molesta en la piel que provoca comezón o picazón. Puede ser causada por alergias, irritaciones o picaduras de insectos. Es importante no rascarse para evitar daños en la piel."},
  {"palabra": "Posesión", "definicion": "Se refiere a tener algo bajo tu control o propiedad. Es cuando algo te pertenece y puedes usarlo o disponer de ello como quieras. Por ejemplo, si tienes un juguete, ese juguete es tu posesión porque lo tienes y puedes jugar con él cuando quieras."},
  {"palabra": "Potronares", "definicion": "Palabra que proviene del ámbito rural y se refiere a los corrales o cercados donde se resguardan los potros jóvenes para su cuidado y entrenamiento. Es un término usado en el mundo ecuestre para designar áreas destinadas al desarrollo y protección de caballos jóvenes."},
  {"palabra": "Preparó", "definicion": "Es una forma del verbo \"preparar\" en tiempo pasado: él o ella preparó. Significa que alguien organizó o dispuso algo con anticipación para un propósito, como preparar comida, estudiar para un examen o alistarse para un evento."},
  {"palabra": "Presagiaba", "definicion": "Significa prever o anticipar algo, especialmente algo malo o desafortunado que pueda ocurrir en el futuro. Es como presentir un evento antes de que suceda, basado en señales o indicios. Por ejemplo, si el cielo está oscuro y hay relámpagos, se puede presagiar una tormenta."},
  {"palabra": "Presencia", "definicion": "Es la sensación de estar presente o cerca de algo o alguien. Se refiere a la existencia física o la atención que alguien o algo recibe. Es sentir que algo o alguien está ahí, ya sea físicamente o de manera perceptible."},
  {"palabra": "Proposición", "definicion": "Idea o afirmación que se presenta para ser considerada o discutida. Es como una declaración que expresa algo que se cree o se propone como verdadero o posible. Por ejemplo, \"El sol es una estrella\" es una proposición sobre el sol."},
  {"palabra": "Protocolos", "definicion": "Conjuntos de reglas o normas que se siguen para hacer algo de manera organizada y correcta. Son como instrucciones que indican cómo deben comportarse las personas o los dispositivos en ciertas situaciones, como en comunicaciones de redes o procedimientos médicos."},
  {"palabra": "Pubertad", "definicion": "Es una etapa de la vida, más o menos entre los 10 y los 14 años, en la que el cuerpo y las emociones cambian mucho: crecemos rápido, la voz cambia y poco a poco empezamos a convertirnos en adultos. En el libro, la voz de Alejandro está cambiando por la pubertad."},
  {"palabra": "Pupa", "definicion": "Es el término usado en biología para describir la etapa de transformación de un insecto, como una mariposa o un escarabajo, entre la fase de larva y la de adulto. Durante esta etapa, el insecto está dentro de un capullo o envoltura, donde experimenta cambios drásticos para convertirse en su forma adulta."},
  {"palabra": "Pánico", "definicion": "Es un miedo intenso y repentino que te hace perder el control. Es una sensación abrumadora de temor que puede provocar reacciones extremas, como correr o gritar."},
  {"palabra": "Quirófano", "definicion": "Es una sala especial en un hospital donde los médicos realizan cirugías. Está equipado con herramientas médicas y tecnología avanzada para garantizar un entorno estéril y seguro durante los procedimientos quirúrgicos."},
  {"palabra": "Químico", "definicion": "Se refiere a alguien que estudia y trabaja con sustancias y reacciones químicas. También se usa para describir cualquier cosa relacionada con la química, como productos químicos o procesos de laboratorio. Los químicos juegan un papel importante en la creación de medicamentos, materiales y muchos otros productos que usamos en la vida diaria."},
  {"palabra": "Rascó", "definicion": "Es una palabra que se usa para describir la acción de frotar suavemente una superficie con las uñas o con un objeto puntiagudo para aliviar picazón o irritación en la piel. Por ejemplo, cuando sientes comezón, puedes rascarte para sentir alivio."},
  {"palabra": "Rastro", "definicion": "Término que se refiere a la huella o marca dejada por algo o alguien al pasar. Puede ser un indicio que permite seguir el camino o la pista de algo o alguien. Por ejemplo, un rastro puede ser una serie de pisadas en el suelo o cualquier evidencia dejada detrás. También puede referirse a un mercado donde se venden artículos usados o de segunda mano."},
  {"palabra": "Reaccionaba", "definicion": "Significa responder a algo, ya sea física, emocional o mentalmente. Es la forma en que interactuamos con el entorno, como sonreír ante una broma o apartar la mano al tocar algo caliente."},
  {"palabra": "Reaparecían", "definicion": "Indica que algo previamente ausente o no visible vuelve a manifestarse o hacerse presente en un contexto específico, sugiriendo una repetición de la acción de aparecer o volver a ser perceptible después de haber estado oculto, ausente o no disponible durante un período anterior."},
  {"palabra": "Recurrente", "definicion": "Significa algo que ocurre repetidamente o que vuelve a suceder con frecuencia. Por ejemplo, un dolor recurrente es aquel que aparece una y otra vez. En resumen, es algo que se repite en el tiempo de manera constante."},
  {"palabra": "Reflejo", "definicion": "Es una respuesta automática del cuerpo ante un estímulo. Por ejemplo, cuando te tocas la mano con algo caliente, tu cuerpo reacciona retirando la mano rápidamente para evitar quemaduras. Es una forma de protección natural que ocurre sin que tengas que pensar en ello."},
  {"palabra": "Refugio", "definicion": "Se refiere a un lugar donde estos insectos encuentran condiciones adecuadas para vivir y reproducirse. Puede ser cualquier área con agua estancada, como charcos, estanques o recipientes con agua acumulada. Estos lugares son propicios para el desarrollo de larvas de mosquitos, lo que aumenta el riesgo de transmisión de enfermedades como el dengue o la malaria."},
  {"palabra": "Repetía", "definicion": "Palabra que usamos cuando hacemos algo otra vez, como decir las mismas palabras o hacer la misma acción más de una vez. Por ejemplo, si dices algo dos veces, \"repetir\" significa que lo dijiste otra vez exactamente igual. Es como volver a hacer algo que ya hiciste antes."},
  {"palabra": "Replicó", "definicion": "Verbo que significa responder de manera rápida y argumentativa a algo que otra persona dijo o preguntó. Es como cuando contestas a una opinión o cuestionamiento con tus propios argumentos o comentarios. Es una forma de expresar tu punto de vista de manera directa y clara."},
  {"palabra": "Reportó", "definicion": "Significa informar sobre algo. Cuando alguien reporta, está contando lo que pasó o dando detalles sobre un evento, situación o problema. Es como dar un informe o hacer una declaración sobre algo que sucedió."},
  {"palabra": "Reproducirse", "definicion": "Significa que los seres vivos hacen más de sí mismos. Es el proceso donde los organismos crean descendientes similares a ellos mismos. Por ejemplo, los animales tienen crías y las plantas producen semillas para generar nuevas plantas. Es esencial para la supervivencia de las especies."},
  {"palabra": "Resarcirlo", "definicion": "Significa compensar o reparar un daño o perjuicio causado a alguien, devolviéndole algo equivalente al daño sufrido para hacerle justicia y restaurar la situación afectada."},
  {"palabra": "Resbaló", "definicion": "Significa perder el equilibrio y deslizarse inesperadamente, usualmente por una superficie resbaladiza o irregular. Por ejemplo, cuando alguien camina sobre hielo y sus pies se mueven sin control."},
  {"palabra": "Retornaría", "definicion": "Significa volver o regresar a un lugar, situación o condición previa. Es como dar marcha atrás para volver al punto de partida o a una situación anterior. Por ejemplo, si alguien dice \"retornaría a mi país de origen\", significa que volvería a su país de nacimiento o donde solía vivir."},
  {"palabra": "Retumbantes", "definicion": "Es un adjetivo que describe algo que produce un sonido fuerte y resonante, como un trueno o un tambor. Por ejemplo, \"los retumbantes truenos anunciaron la llegada de la tormenta\". Es una palabra que se usa para destacar la intensidad del sonido."},
  {"palabra": "Reutilizables", "definicion": "Es un adjetivo que describe objetos que pueden ser usados múltiples veces sin perder su función o calidad. Son productos diseñados para ser usados una y otra vez, en lugar de ser desechados después de un solo uso, lo que ayuda a reducir el desperdicio y proteger el medio ambiente."},
  {"palabra": "Revelaron", "definicion": "Mostrar algo que estaba oculto o desconocido. Es como cuando levantas una cortina y revelas lo que está detrás. En el contexto de información, revelar es hacer pública algo que antes era secreto o desconocido."},
  {"palabra": "Roce", "definicion": "Contacto físico entre dos superficies que produce fricción o rozamiento. Por ejemplo, cuando frotas tus manos juntas, sientes el roce. También puede significar un encuentro breve o una disputa leve entre personas o cosas."},
  {"palabra": "Roncha", "definicion": "Es una protuberancia rojiza en la piel que resulta de una reacción alérgica o picadura de insecto. Se caracteriza por su picazón y enrojecimiento. A menudo desaparece por sí sola, pero puede aliviarse con medicamentos tópicos anti-picazón."},
  {"palabra": "Rondaban", "definicion": "Forma del verbo \"rondar\", que significa merodear o estar cerca de algo o alguien, como un lugar o una persona, usualmente de manera sospechosa o vigilante. Por ejemplo, si se dice que los ladrones rondaban la casa, significa que estaban cerca, posiblemente planeando algo malo."},
  {"palabra": "Rumoraban", "definicion": "Es una forma verbal que significa que varias personas están hablando o comentando algo entre sí de manera informal y generalmente en secreto. Es como un murmullo de conversaciones que se extienden entre la gente."},
  {"palabra": "Saciarse", "definicion": "Significa comer o beber lo suficiente para sentirse lleno o satisfecho. Cuando te sacias, tu cuerpo ha recibido la cantidad adecuada de alimentos o líquidos, y ya no sientes hambre o sed. Es importante escuchar a tu cuerpo y no comer más de lo necesario para evitar sentirte incómodo."},
  {"palabra": "Sacudirse", "definicion": "Significa moverse bruscamente para deshacerse de algo, como el polvo o la suciedad, de manera vigorosa. También puede referirse a liberarse de preocupaciones o problemas de manera enérgica. Es como cuando un perro se sacude después de bañarse para quitarse el agua."},
  {"palabra": "Saneamiento", "definicion": "Se refiere a la acción de limpiar y desinfectar un lugar para mantenerlo seguro y saludable. Incluye la eliminación de desechos, la purificación del agua y la higiene ambiental para prevenir enfermedades. Es fundamental para garantizar un entorno habitable y proteger la salud pública."},
  {"palabra": "Sanidad", "definicion": "Se refiere al estado de salud tanto física como mental de una persona o de un grupo de personas. También puede referirse al conjunto de medidas y políticas que se aplican para promover y proteger la salud de la población, como la prevención de enfermedades y la atención médica."},
  {"palabra": "Satisfactorio", "definicion": "Significa que algo cumple con tus expectativas o te hace sentir contento porque has logrado lo que querías o necesitabas. Es como cuando algo te deja satisfecho o te hace sentir bien.", "alias": ["satisfactorios"]},
  {"palabra": "Sentenció", "definicion": "Significa que alguien dijo algo de forma firme y definitiva, como una conclusión que no admite dudas. En el libro, el inspector \"sentenció\" cuando terminó de explicar con seguridad cómo se transmite la enfermedad."},
  {"palabra": "Sigilo", "definicion": "Actuar con discreción y cuidado para no ser detectado o notado. Es mantener algo en secreto o realizar una acción sin que otros lo perciban. Es como moverse en la oscuridad sin hacer ruido, evitando llamar la atención."},
  {"palabra": "Sintomatología", "definicion": "Se refiere a los síntomas que una persona experimenta cuando está enferma o tiene algún problema de salud. Son señales que indican que algo no está bien en el cuerpo, como fiebre, dolor de cabeza, tos, entre otros."},
  {"palabra": "Sobrenatural", "definicion": "Se refiere a cosas o eventos que están más allá de la comprensión o explicación científica. Son fenómenos que parecen desafiar las leyes naturales, como fantasmas, magia o poderes paranormales."},
  {"palabra": "Sobrevivir", "definicion": "Significa continuar viviendo o existiendo a pesar de enfrentar desafíos, peligros o situaciones difíciles. Es adaptarse y mantenerse con vida, superando obstáculos y adversidades. Es la capacidad de mantenerse firme y seguir adelante, incluso en las circunstancias más difíciles."},
  {"palabra": "Soluciones", "definicion": "Se refiere a respuestas o métodos para resolver problemas o satisfacer necesidades. Son ideas o acciones que ayudan a superar dificultades o alcanzar objetivos. Pueden ser estrategias, productos o servicios diseñados para resolver una situación específica."},
  {"palabra": "Sombras", "definicion": "Se refiere a las áreas oscuras que se forman cuando la luz es bloqueada por un objeto. Son las partes donde la luz no llega directamente. Las sombras se producen cuando un objeto obstruye la luz, creando una zona más oscura detrás de él."},
  {"palabra": "Sudoración", "definicion": "Es el proceso por el cual el cuerpo libera líquido a través de los poros de la piel cuando tiene calor, está nervioso o haciendo ejercicio. Este líquido se llama sudor y ayuda a refrescar el cuerpo y regular su temperatura."},
  {"palabra": "Sueros", "definicion": "Se refiere a líquidos medicinales que se administran por vía intravenosa para rehidratar o suministrar nutrientes al cuerpo. Son utilizados en hospitales para tratar deshidratación, deficiencias nutricionales u otras condiciones médicas."},
  {"palabra": "Sugirió", "definicion": "Palabra que significa proponer una idea o una opinión de manera amable. Cuando alguien sugiere algo, está ofreciendo una sugerencia o recomendación sobre qué hacer o cómo actuar en una situación determinada. Es como ofrecer una idea para considerar o seguir."},
  {"palabra": "Sujetaba", "definicion": "Significa sostener firmemente algo con las manos u otro medio para evitar que se caiga o se mueva. Es como cuando agarras un objeto para que no se caiga al suelo."},
  {"palabra": "Sumergidas", "definicion": "Se refiere a los huevos de mosquitos del dengue que están bajo el agua estancada. Estos huevos están sumergidos en agua estancada, donde se desarrollan en larvas y luego en mosquitos adultos. Es importante eliminar recipientes con agua estancada para evitar la proliferación de mosquitos transmisores del dengue.", "alias": ["sumergida"]},
  {"palabra": "Sumergió", "definicion": "Es la forma pasada del verbo sumergir, que significa meter algo completamente debajo de un líquido. Por ejemplo, si sumerges una esponja en agua, la metes completamente en el agua. Es como cuando te sumerges en una piscina y quedas completamente bajo el agua."},
  {"palabra": "Susurró", "definicion": "Significa hablar en voz baja o murmurar. Es cuando alguien emite sonidos suaves con la boca casi cerrada, como un secreto compartido en voz baja. Es una forma de comunicación discreta, típica cuando se quiere decir algo en privado o en secreto."},
  {"palabra": "Síntoma", "definicion": "Es una señal o manifestación física que indica la presencia de una enfermedad o trastorno en el cuerpo. Puede ser dolor, tos, fiebre, entre otros, y ayuda a los médicos a diagnosticar y tratar problemas de salud."},
  {"palabra": "Tajante", "definicion": "Significa ser claro, directo y sin rodeos al expresar una opinión o tomar una decisión. Cuando alguien es tajante, no deja lugar a dudas o interpretaciones diferentes, comunicándose de manera firme y definitiva."},
  {"palabra": "Tarima", "definicion": "Plataforma elevada, por lo general de madera, utilizada para diferentes propósitos. Puede servir como escenario en eventos, plataforma de trabajo en construcción o como base para muebles. Es una superficie plana y resistente que facilita diversas actividades."},
  {"palabra": "Temor", "definicion": "Es una sensación de miedo o preocupación que experimentamos cuando creemos que algo malo puede suceder. Es una emoción natural que nos alerta sobre posibles peligros o amenazas. Sentimos temor cuando percibimos situaciones que nos hacen sentir inseguros o vulnerables."},
  {"palabra": "Teoría", "definicion": "Se refiere a una explicación o conjunto de ideas que intenta explicar cómo funcionan las cosas en el mundo. Es como una suposición bien pensada respaldada por evidencia. Ayuda a entender y predecir fenómenos, pero siempre está sujeta a ser probada y modificada según nuevas observaciones."},
  {"palabra": "Tildaron", "definicion": "Significa que una persona o un grupo de personas criticaron o señalaron algo negativo sobre otra persona o una situación. Es como cuando marcan algo con un \"error\" o una crítica. Por ejemplo, si alguien dice \"lo tildaron de mentiroso\", significa que lo acusaron de mentir."},
  {"palabra": "Titilaban", "definicion": "Significa que algo o alguien emitía una luz débil y intermitente, como cuando una vela parpadea suavemente. Es como un destello leve y repetitivo. Por ejemplo, las estrellas titilaban en el cielo oscuro de la noche."},
  {"palabra": "Toxicidad", "definicion": "Se refiere a lo dañino que algo puede ser para tu cuerpo o ambiente. Por ejemplo, ciertas sustancias químicas, relaciones tóxicas o ambientes contaminados pueden causar efectos negativos en tu salud o bienestar. Es importante evitar o eliminar lo que es tóxico para protegerte a ti mismo y a tu entorno."},
  {"palabra": "Transformar", "definicion": "Significa cambiar algo de una forma a otra. Es como convertir o modificar algo para que sea diferente. Por ejemplo, transformar una hoja en una figura de origami es cambiar su forma. En resumen, transformar implica darle una nueva apariencia o función a algo."},
  {"palabra": "Transmitió", "definicion": "Significa enviar o comunicar información, ideas o emociones de una persona a otra, usualmente a través de palabras, gestos, escritura, o medios tecnológicos como radio, televisión o internet. Es como pasar un mensaje de un lugar a otro para que otra persona lo reciba y entienda."},
  {"palabra": "Trasladarlo", "definicion": "Mover algo o a alguien de un lugar a otro. Por ejemplo, llevar un objeto o cambiar de residencia. Es como cuando cambias un mueble de posición en tu habitación o cuando te mudas a otra casa."},
  {"palabra": "Tregua", "definicion": "Es un descanso temporal en una disputa o conflicto. Durante una tregua, las partes involucradas acuerdan diferencias de manera pacífica."},
  {"palabra": "Trompa", "definicion": "Es un término que se refiere a la boca de ciertos insectos. Se usa en el contexto de cómo los insectos propagan un virus, es decir, cómo ciertos insectos están transmitiendo un virus a través de sus bocas."},
  {"palabra": "Urgencias", "definicion": "Son situaciones que requieren atención inmediata debido a la gravedad o urgencia de un problema médico, como accidentes o enfermedades repentinas. Los servicios de urgencias proporcionan atención médica rápida y especializada para tratar estas situaciones urgentes."},
  {"palabra": "Vaciaron", "definicion": "Es la forma pasada del verbo \"vaciar\", que significa sacar el contenido de algo, dejándolo vacío. Por ejemplo, si derramas el agua de un vaso, lo vacías. En este caso, \"vaciaron\" indica que alguien o algo ha hecho que algo esté vacío."},
  {"palabra": "Valentía", "definicion": "Es tener el coraje y la fortaleza para enfrentar situaciones difíciles o miedos, sin dejarse vencer por el miedo. Es actuar con determinación y firmeza, incluso cuando hay riesgos o adversidades. Es hacer lo correcto, aunque sea difícil."},
  {"palabra": "Vehemencia", "definicion": "Expresar algo con intensidad y pasión, sin contenerse. Es como cuando hablas o actúas con mucha fuerza y emoción, mostrando tu convicción o entusiasmo de manera enérgica y decidida. Es como un torrente de emociones que se desborda."},
  {"palabra": "Verbo", "definicion": "Es una palabra que describe una acción, como \"correr\", \"saltar\" o \"pensar\". Pero en el libro, cuando el alcalde dice \"mucha poesía y poco verbo\", la usa de otra forma: quiere decir que el inspector habla muy bonito pero no dice nada concreto ni propone acciones."},
  {"palabra": "Vigilar", "definicion": "Significa estar atento y cuidar de algo o alguien para protegerlo o mantenerlo seguro. Es como estar alerta y observar constantemente para prevenir problemas o peligros. Por ejemplo, los guardias vigilan un lugar para asegurarse de que todo esté en orden."},
  {"palabra": "Virus", "definicion": "Es un pequeño organismo microscópico que puede causar enfermedades. No es capaz de reproducirse por sí mismo, por lo que infecta células de organismos vivos para multiplicarse y propagarse. Pueden causar desde simples resfriados hasta enfermedades más graves como la gripe o el COVID-19."},
  {"palabra": "Vivencias", "definicion": "Se refiere a las experiencias que vivimos a lo largo de nuestra vida, como recuerdos, momentos especiales o situaciones que nos enseñan algo importante. Son las cosas que nos suceden y nos ayudan a crecer, aprender y entender el mundo que nos rodea."},
  {"palabra": "Víctima", "definicion": "Alguien que sufre daño, dolor o pérdida debido a acciones, circunstancias o eventos negativos. Puede ser víctima de un crimen, accidente o cualquier situación adversa. La víctima no es responsable de lo que le sucede y merece apoyo y justicia."},
  {"palabra": "Vítores", "definicion": "usan para mostrar apoyo, felicitar o animar a alguien en eventos como celebraciones, manifestaciones o competiciones. Es una forma de demostrar entusiasmo y reconocimiento hacia algo o alguien."},
  {"palabra": "Yacía", "definicion": "Es una forma del verbo \"yacer\", que significa estar acostado o reposando en posición horizontal, usualmente sobre una superficie plana. Por ejemplo, podrías decir \"el perro yacía en el sofá\" para indicar que el perro estaba recostado en el sofá."},
  {"palabra": "Zancuda", "definicion": "Término que se usa en relación con el mosquito Aedes aegypti, el cual es portador del virus del dengue. Se llama \"zancuda\" por sus patas largas y delgadas. Este mosquito es el principal transmisor del dengue al picar a las personas infectadas y luego transmitir el virus a otras personas sanas a través de sus picaduras."},
  {"palabra": "Zancudo", "definicion": "Se refiere a un tipo de mosquito (Aedes aegypti) que puede transmitir enfermedades como el dengue, el zika y el chikungunya. Es importante controlar su población para prevenir brotes de estas enfermedades."},
  {"palabra": "Zigzagueaban", "definicion": "Es un verbo que describe un movimiento en forma de zigzag, es decir, de lado a lado en una serie de líneas que forman ángulos irregulares. Por ejemplo, cuando alguien camina de manera serpenteante o un objeto se desplaza en un patrón de vaivén."}
];

// Minúsculas y sin tildes: solo para BUSCAR y agrupar por letra.
export function normalizar(texto: string) {
  return texto.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export function letraInicial(palabra: string) {
  return normalizar(palabra).charAt(0).toUpperCase();
}

const CLAVES_DENGUE = ["dengue", "mosquito", "aedes", "zancud"];

export function esDelDengue(p: Palabra) {
  const d = p.definicion.toLowerCase();
  return CLAVES_DENGUE.some((k) => d.includes(k));
}

// Búsqueda EXACTA (respetando tildes) para marcar palabras dentro del libro:
// así "Lozania" (la ciudad) no se confunde con "Lozanía" (frescura).
let lookupCache: Map<string, Palabra> | null = null;
export function buscarExacta(token: string): Palabra | undefined {
  if (!lookupCache) {
    lookupCache = new Map();
    for (const p of DICCIONARIO) {
      lookupCache.set(p.palabra.toLowerCase(), p);
      for (const a of p.alias ?? []) lookupCache.set(a.toLowerCase(), p);
    }
  }
  return lookupCache.get(token.toLowerCase());
}

// Palabras del texto (letras con tildes y ñ).
export const TOKEN_RE = /[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g;

// Voz del diccionario: primero intenta el audio pregrabado con la voz colombiana
// "Gonzalo" (public/audio/diccionario/<palabra>.mp3). Si no existe, usa la voz del
// navegador, prefiriendo una voz de Colombia y las voces "naturales".
export function slugPalabra(palabra: string) {
  return palabra.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

let audioActual: HTMLAudioElement | null = null;

function detener() {
  try { window.speechSynthesis.cancel(); } catch { /* sin síntesis */ }
  if (audioActual) { audioActual.pause(); audioActual = null; }
}

function vozDelNavegador(texto: string) {
  try {
    const u = new SpeechSynthesisUtterance(texto);
    u.lang = "es-CO";
    u.rate = 0.92;
    const voces = window.speechSynthesis.getVoices().filter((v) => v.lang.toLowerCase().startsWith("es"));
    const natural = (v: SpeechSynthesisVoice) => /natural|neural|online|google/i.test(v.name);
    const voz =
      voces.find((v) => /co/i.test(v.lang) && natural(v)) ||
      voces.find((v) => /co/i.test(v.lang)) ||
      voces.find(natural) ||
      voces[0];
    if (voz) u.voice = voz;
    window.speechSynthesis.speak(u);
  } catch {
    // Sin síntesis de voz en este navegador: simplemente no suena.
  }
}

export function hablar(texto: string) {
  detener();
  // Las llamadas del diccionario y del lector usan el formato "Palabra. definición".
  const palabra = texto.split(".")[0]?.trim();
  const p = palabra ? buscarExacta(palabra) : undefined;
  if (!p || typeof Audio === "undefined") { vozDelNavegador(texto); return; }
  const audio = new Audio(`/audio/diccionario/${slugPalabra(p.palabra)}.mp3`);
  audioActual = audio;
  audio.play().catch(() => { if (audioActual === audio) { audioActual = null; vozDelNavegador(texto); } });
  audio.onerror = () => { if (audioActual === audio) { audioActual = null; vozDelNavegador(texto); } };
}
